
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jgranados.compi1_2025.flexycup.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 6;
  public static final int RESTA = 4;
  public static final int error = 1;
  public static final int SUMA = 3;
  public static final int DIVISION = 5;
  public static final int P_COMA = 2;
  public static final int EOF = 0;
  public static final int ENTERO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "P_COMA",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "ENTERO"
  };
}

